### ISSUE TITLE
Get com.browserstack.local.LocalException: Could not connect to www.browserstack.com! when starting local with proxy

### ISSUE THREAD

**Issue by MarinaRappoport** [browserstack/browserstack-local-java#23]
I get an exception (com.browserstack.local.LocalException: Could not connect to www.browserstack.com!) on l.start(options) when using following code:
`
Local l = new Local();
            Map<String, String> options = new HashMap<String, String>();
            options.put("key", accessKey);
            options.put("forcelocal", "true");
            options.put("forceproxy", "true");
            options.put("proxyHost", "localhost");
            options.put("proxyPort", "8080");
            `l.start(options);`

The same standalone command works fine:
`BrowserStackLocal --key <accessKey> --local-proxy-host localhost --local-proxy-port 8080 --force-local --force-proxy`

**Comment by punitx** [comment]
The params `proxyHost` and `local-proxy-host` serve a different purpose. If you want to use the same params as you used in the standalone command, please use the following snippet:

`Local l = new Local();
Map<String, String> options = new HashMap<String, String>();
options.put("key", accessKey);
options.put("forcelocal", "true");
options.put("forceproxy", "true");
options.put("localProxyHost", "localhost");
options.put("localProxyPort", "8080");
l.start(options);`

More information about the params can be found [here](https://www.browserstack.com/local-testing#config-proxy-server)

**Comment by MarinaRappoport** [comment]
@punitx thanks a lot, it works fine!
