### ISSUE TITLE
Browaserstack local doesn't support local-proxy options

### ISSUE THREAD

**Issue by krsenthil** [browserstack/browserstack-local-java#28]
Current version of Local doesn't support for the local-proxy options including local-proxy-host, local-proxy-port and --force-proxy. 

This is required for me to implement mocking some of the data supplied to native application through the automation framework. Handling these through the shell scripts only makes the implementation very clumsy. Hope fully the support will be added sooner.

**Comment by mohitmun** [comment]
Thanks for letting us know @krsenthil, will soon add support for those flags. keeping this issue open.

**Comment by ray-pankaj** [comment]
@krsenthil These options do work. See #32 . Closing this issue.
