### ISSUE TITLE
BrowserMobProxy with browserstack is not intercepting the response

### ISSUE THREAD

**Issue by arihan** [browserstack/browserstack-local-java#39]
I am using JAVA + SELENIUM web-driver + browser mobproxy + browserstacklocal ( embeded) 

    compile 'com.browserstack:browserstack-local-java:1.0.2'
    compile 'net.lightbody.bmp:browsermob-core:2.1.5'

Locally its working fine as I am able to intercept the api response and override the response code ( as example 200-OK to 502-BAD_GATEWAY)

However while running this test in the browserstack , its not working as seems mobproxy is not intercepting the response and overriding that. So assertion fails in the test steps. Other tests which does not depend on mobproxy are working fine in browsestack.

    Proxy seleniumProxy = ProxyUtils.getInstance().createSeleniumProxy();
    String host=seleniumProxy.getHttpProxy()
                .substring(0,seleniumProxy.getHttpProxy().indexOf(":"));
    String port=seleniumProxy.getHttpProxy()
                .substring(seleniumProxy.getHttpProxy()
                .indexOf(":")+1,seleniumProxy.getHttpProxy().length());
    browserStackLocalArgs.put("key", <key>);
    browserStackLocalArgs.put("localIdentifier", <identifier>);
    browserStackLocalArgs.put("forcelocal", "true");
    browserStackLocalArgs.put("force", "true");
    browserStackLocalArgs.put("forceproxy", "true");
    browserStackLocalArgs.put("localProxyHost", host);
    browserStackLocalArgs.put("localProxyPort", String.valueOf(port));
    browserStackLocalArgs.put("--daemon", "start");
    browserStackLocal.start(browserStackLocalArgs);

I have used both localProxyHost and -local-proxy-host but no luck. 
I am adding the set capability for the browserstack as well.

    ChromeOptions chromeOptions = new ChromeOptions();
    chromeOptions.setCapability(CapabilityType.PROXY, proxy);
    browserStackCapabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions); 

While doing ps -ef | grep browserstack it returns me

505   921     1   0  6:33pm ??         0:00.86 /Users/ITAS4/.browserstack/BrowserStackLocal -d start key -forceproxy -localIdentifier browserstack_local_machine -force -localProxyPort 49676 ---daemon start -forcelocal -localProxyHost CHISIMAC0123.local -daemonInstance

505   943   921   0  6:33pm ??         0:02.29 /Users/ITAS4/.browserstack/BrowserStackLocal key -forceproxy -localIdentifier browserstack_local_machine-browserstack-fork-0 -localProxyPort 49676 ---daemon start -forcelocal -localProxyHost CHISIMAC0123.local -daemonInstance

505   944   921   0  6:33pm ??         0:00.79 /Users/ITAS4/.browserstack/BrowserStackLocal key -forceproxy -localIdentifier browserstack_local_machine-browserstack-fork-1 -localProxyPort 49676 ---daemon start -forcelocal -localProxyHost CHISIMAC0123.local -daemonInstance

505   945   921   0  6:33pm ??         0:00.80 /Users/ITAS4/.browserstack/BrowserStackLocal key -forceproxy -localIdentifier browserstack_local_machine-browserstack-fork-2 -localProxyPort 49676 ---daemon start -forcelocal -localProxyHost CHISIMAC0123.local -daemonInstance

505   946   921   0  6:33pm ??         0:00.79 /Users/ITAS4/.browserstack/BrowserStackLocal key -forceproxy -localIdentifier browserstack_local_machine-browserstack-fork-3 -localProxyPort 49676 ---daemon start -forcelocal -localProxyHost CHISIMAC0123.local -daemonInstance

505   947   921   0  6:33pm ??         0:00.80 /Users/ITAS4/.browserstack/BrowserStackLocal key -forceproxy -localIdentifier browserstack_local_machine-browserstack-fork-4 -localProxyPort 49676 ---daemon start -forcelocal -localProxyHost CHISIMAC0123.local -daemonInstance

**Comment by pulkitsharma07** [comment]
Hey ! 

We were not able to find your email id to contact you regarding this issue.
Can you please drop a mail to support@browserstack.com, they would love to help you !

Thanks.

**Comment by arihan** [comment]
@pulkitsharma07 Thanks. I sent the email through my email id which registered with browserstack and waiting for their response.

**Comment by arihan** [comment]
working fine
