### ISSUE TITLE
can't start with logfile option

### ISSUE THREAD

**Issue by tmshft** [browserstack/browserstack-local-java#49]
## Expected Behavior

com.browserstack.local.Local instance should start with `logfile` option.

## Actual Behavior

Local instance does not start.
And it caused LocalException
Without `logfile` option it started successfully.

I'd like to have some log of browserstacklocal.
Could you tell me what is the solution?

## Steps to Reproduce the Problem

  1. set arguments
  2. start local instance

## browserstack local arguments

```java
bsLocalArgs.put("v", "true");
bsLocalArgs.put("logfile", "/browserstack/logs.txt");
```

## Platform details
 
  1. browserstack-local-java version:1.1.3
  2. java version: jdk-8.0.252.09-hotspot
  3. os type and version:Windows 10
  4. Selenium ver: 3.14159

## Details

error log

```log
com.browserstack.local.LocalException: Could not connect to -logfile due to Network issues. Please check your internet connection or if you are behind proxy please use our proxy options. For more details https://www.browserstack.com/local-testing#modifiers
  at com.browserstack.local.Local.start(Local.java:80)
  at jp.hoge.automation.driver.BrowserStackLocalExecutor.setLocal(BrowserStackLocalExecutor.java:46)
```

**Comment by Raj-7799** [comment]
Documentation had incorrect argument. Changed the argument to `logFile`.
Revision PR : https://github.com/browserstack/browserstack-local-java/pull/50.
Closing this.
