### ISSUE TITLE
Request support for --use-ca-certificate flag

### ISSUE THREAD

**Issue by zhlim22** [browserstack/browserstack-local-java#72]
## Expected Behavior

Should be able to include --use-ca-certificate flag as per the binrary: https://www.browserstack.com/docs/local-testing/binary-params

## Actual Behavior

Not able/no idea on how to include --use-ca-certificate flag using this library

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Platform details
 
  1. browserstack-local-java version: 1.0.7
  2. java version: 11
  3. os type and version: Windows 10

## Details

I noticed in the browserstack page on the flags for local binary, it is possible to use the --use-ca-certificate flag but we can't do/do not know how to do the same using this library. If it is already possible to do so would like to request that this gets added to the readme. thank you!

**Comment by ganesh-gsk** [comment]
Hi @zhlim22, 

You can try adding this flag of --use-ca-certificate similar to the --pac-file flag shown in this repository. 

Also alternatively, you can follow this documentation https://www.browserstack.com/docs/automate/selenium/accept-insecure-certificates to accept all SSL certificates directly using the acceptInsecureCerts capability. 

In case of further issues, you can reach out to us directly through our Contact Us page - https://www.browserstack.com/contact

**Comment by zhlim22** [comment]
Hi @ganesh-gsk ,

Using the -use-ca-certificate flag works fine for my case. Closing this issue now.

Thank you!
